---
title: "Fig4"
author: "Bre Rivera Waterman"
date: "2024-02-22"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(colourpicker)
library(lubridate)
library(emmeans)
library(sf)
library(ggspatial)
library(spData)
library(ggpmisc)
#install.packages("ggpubr")
library("rstudioapi")

current_path <- rstudioapi::getActiveDocumentContext()$path 
setwd(dirname(current_path))
setwd("./../")
getwd()
```
 - getting data
```{r}
combods <- read.csv("./ICON-ModEx_Open_Manuscript/ICON-ModEx_Combined_Predicted_Observed_Respiration_Rates.csv") %>% filter(!is.na(Observed_Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment),!is.na(Predicted_Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment)) %>% filter(Observed_Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment > -9990, Predicted_Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment > -9990 )

```

## Fig 4 
- generating plots
```{r}
combods <- combods %>% filter(Latitude < 50 & Latitude > 20) %>% mutate(LogObs = Observed_Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment, LogPred = Predicted_Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment)

library(RColorBrewer)


Obs <- ggplot(usa) +
  geom_sf(color = "#2b2b2b", fill = "#FCFCFC", size=0.125) +
  coord_sf(crs = st_crs("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"), datum = NA) +
  geom_spatial_point(data=combods, aes(x=Longitude,y=Latitude, fill = log(-LogObs+1)), pch = 21, size =4) +     
  #scale_shape_manual(values = c(16, 8)) +
   # scale_size_manual(values = c(4, 8)) +
  scale_fill_distiller(palette = "Spectral",  #YlOrRd
                        limits = c(min(log(0+1)), max(log(4000+10)) )) + 
  ylab("") + 
  xlab("") +
   ggtitle("Observed respiration rates at sampled sites") +
 theme_classic() +
   theme(panel.background = element_rect(fill = "white"), text = element_text(size = 12), legend.position ="none") +
    labs(fill = "log(Resp. + 5)") 

#aliceblue
  
 Pred<- 
  ggplot(usa) +
  geom_sf(color = "#2b2b2b", fill = "#FCFCFC", size=0.125) +
  coord_sf(crs = st_crs("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"), datum = NA) +
  geom_spatial_point(data=combods, aes(x=Longitude,y=Latitude, fill = log(-LogPred+1)), pch = 21, size =4) +     
  #scale_shape_manual(values = c(16, 8)) +
   # scale_size_manual(values = c(4, 8)) +
  scale_fill_distiller( palette = "Spectral", 
                        limits = c(min(log(0+1)), max(log(4000+10)) ) )  + 
  ylab("") + 
  xlab("")  +
   ggtitle("Predicted respiration rates at sampled sites") +
     #   annotation_scale(location = "bl", width_hint = 0.3,  pad_x = unit(0.1, "in"), pad_y = unit(0.1, "in")) +
  theme_classic() +
   theme(panel.background = element_rect(fill = "white"), text = element_text(size = 12), legend.position = "bottom") +
       labs(fill = "log(Resp. + 1)") 
 
Meanerror<- 
  ggplot(usa) +
  geom_sf(color = "#2b2b2b", fill = "#FCFCFC", size=0.125) +
  coord_sf(crs = st_crs("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"), datum = NA) +
  geom_spatial_point(data=combods, aes(x=Longitude,y=Latitude, fill = log(combods$mean.error)), pch = 21, size =4) +     
  #scale_shape_manual(values = c(16, 8)) +
   # scale_size_manual(values = c(4, 8)) +
  scale_fill_distiller( palette = "Spectral") +
                        #limits = c(min(log(0+1)), max(log(4000+10)) ) )  + 
  ylab("") + 
  xlab("")  +
   ggtitle("Mean error") +
     #   annotation_scale(location = "bl", width_hint = 0.3,  pad_x = unit(0.1, "in"), pad_y = unit(0.1, "in")) +
  theme_classic() +
   theme(panel.background = element_rect(fill = "white"), text = element_text(size = 12), legend.position = 0) +
       labs(fill = "Mean error") 
  
Rawerror<- 
  ggplot(usa) +
  geom_sf(color = "#2b2b2b", fill = "#FCFCFC", size=0.125) +
  coord_sf(crs = st_crs("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"), datum = NA) +
  geom_spatial_point(data=combods, aes(x=Longitude,y=Latitude, fill = log(combods$Raw_Error)), pch = 21, size =4) +     
  #scale_shape_manual(values = c(16, 8)) +
   # scale_size_manual(values = c(4, 8)) +
  scale_fill_distiller( palette = "Spectral")  +
                       # limits = c(min((0+1)), max(log(4000+10)) ) )  + 
  ylab("") + 
  xlab("")  +
   ggtitle("Raw error") +
     #   annotation_scale(location = "bl", width_hint = 0.3,  pad_x = unit(0.1, "in"), pad_y = unit(0.1, "in")) +
  theme_classic() +
   theme(panel.background = element_rect(fill = "white"), text = element_text(size = 12), legend.position = "bottom") +
       labs(fill = "Raw error") 


  (Obs / Pred) + (Meanerror / Rawerror) #not sure which error to use

```


